@startuml
title ShoppingCart
entity ShoppingCart <<entity>> {
	/SubTotal : Currency
	/TaxAmount : Currency
	/DiscountAmount : Currency
	/TotalAmount : Currency
}
entity ProductOnCart <<entity>> {
	/Price : Currency
	Quantity : Integer
	/Total : Currency
}

	ShoppingCart "0..*" --> "1..1 Customer" Customer

	ShoppingCart "0..*" --> "0..* ProductsOnCart" ProductOnCart

	ProductOnCart "0..*" --> "1..1 ShoppingCart" ShoppingCart

	ProductOnCart "0..*" --> "1..1 Product" Product
@enduml
